"""empty message

Revision ID: 89ca68e599f1
Revises: 439ca988ffa2
Create Date: 2023-03-07 10:00:07.783504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89ca68e599f1'
down_revision = '439ca988ffa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manager', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('phone')

    op.drop_table('manager')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('user')
    op.drop_table('vehicle')
    with op.batch_alter_table('chargingpile', schema=None) as batch_op:
        batch_op.drop_index('units')

    op.drop_table('chargingpile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chargingpile',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('place', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('units', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('chargingpile', schema=None) as batch_op:
        batch_op.create_index('units', ['units'], unique=False)

    op.create_table('vehicle',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('vehiclename', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('dealcount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('unit', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('time', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=False)

    op.create_table('manager',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('manager', schema=None) as batch_op:
        batch_op.create_index('phone', ['phone'], unique=False)
        batch_op.create_index('email', ['email'], unique=False)

    # ### end Alembic commands ###
