"""empty message

Revision ID: dfb8d45f43c0
Revises: b347a07029b3
Create Date: 2023-03-07 10:22:13.005795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dfb8d45f43c0'
down_revision = 'b347a07029b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_brands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('brand_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('brand_code', sa.String(length=255), nullable=True))
        batch_op.drop_column('ID')
        batch_op.drop_column('品牌代号')
        batch_op.drop_column('名称')

    with op.batch_alter_table('t_cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('car_brand', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('car_introduction', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('car_class', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('car_brand_code', sa.String(length=255), nullable=True))
        batch_op.drop_column('品牌')
        batch_op.drop_column('车型')
        batch_op.drop_column('品牌代号')
        batch_op.drop_column('ID')
        batch_op.drop_column('介绍')

    with op.batch_alter_table('t_carsales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sales', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sale_brand_code', sa.String(length=255), nullable=True))
        batch_op.drop_column('时间')
        batch_op.drop_column('品牌代号')
        batch_op.drop_column('销量')
        batch_op.drop_column('ID')

    with op.batch_alter_table('t_carsinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('hyperlink', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('content', sa.String(length=100), nullable=True))
        batch_op.drop_column('ID')
        batch_op.drop_column('标题')
        batch_op.drop_column('超链接')
        batch_op.drop_column('内容')

    with op.batch_alter_table('t_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sales', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sale_brand_code', sa.String(length=255), nullable=True))
        batch_op.drop_column('时间')
        batch_op.drop_column('品牌代号')
        batch_op.drop_column('销量')
        batch_op.drop_column('ID')

    with op.batch_alter_table('t_stations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('station_class', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('scope', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('count', sa.Integer(), nullable=True))
        batch_op.drop_column('数量')
        batch_op.drop_column('单位')
        batch_op.drop_column('范围')
        batch_op.drop_column('ID')
        batch_op.drop_column('类别')

    with op.batch_alter_table('t_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('isManager', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('用户名')
        batch_op.drop_column('密码')
        batch_op.drop_column('ID')
        batch_op.drop_column('邮箱')
        batch_op.drop_column('是否管理员')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('是否管理员', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('邮箱', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('密码', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('用户名', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('isManager')
        batch_op.drop_column('email')
        batch_op.drop_column('password')
        batch_op.drop_column('username')
        batch_op.drop_column('id')

    with op.batch_alter_table('t_stations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('类别', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('范围', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('单位', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('数量', mysql.INTEGER(display_width=255), autoincrement=False, nullable=True))
        batch_op.drop_column('count')
        batch_op.drop_column('unit')
        batch_op.drop_column('scope')
        batch_op.drop_column('station_class')
        batch_op.drop_column('id')

    with op.batch_alter_table('t_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('销量', mysql.INTEGER(display_width=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('品牌代号', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=True))
        batch_op.add_column(sa.Column('时间', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('sale_brand_code')
        batch_op.drop_column('sales')
        batch_op.drop_column('time')
        batch_op.drop_column('id')

    with op.batch_alter_table('t_carsinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('内容', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('超链接', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('标题', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('content')
        batch_op.drop_column('hyperlink')
        batch_op.drop_column('title')
        batch_op.drop_column('id')

    with op.batch_alter_table('t_carsales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('销量', mysql.INTEGER(display_width=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('品牌代号', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('时间', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('sale_brand_code')
        batch_op.drop_column('sales')
        batch_op.drop_column('time')
        batch_op.drop_column('id')

    with op.batch_alter_table('t_cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('介绍', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('品牌代号', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('车型', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('品牌', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('car_brand_code')
        batch_op.drop_column('car_class')
        batch_op.drop_column('car_introduction')
        batch_op.drop_column('car_brand')
        batch_op.drop_column('id')

    with op.batch_alter_table('t_brands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('名称', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('品牌代号', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('brand_code')
        batch_op.drop_column('brand_name')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
